### ISSUE TITLE
grails 2.4.0

### ISSUE THREAD

**Issue by LucaMansutti** [joergrech/KickstartWithBootstrap#91]
KickstartWithBootstrap not work with grails 2.4.0 why?

**Comment by JohnTheBeloved** [comment]
The plugin's last build uses the resources plugin which was not meant to work with grails 2.4.
Either rebuilding the plugin with the recent build of the resources plugin or refactoring to use the asset pipeline plugin should fix the issue

**Comment by marcellodesales** [comment]
Any detailed instructions to do that?

**Comment by JohnTheBeloved** [comment]
Firstly, are you upgrading your grails application from a previous version of its a new grailsapp based on 2.4.2 version

**Comment by marcellodesales** [comment]
I had a fresh Grails installation of 2.4.3 before giving up...

**Comment by biohazardxxx** [comment]
Same over here with 2.4.4. Please give more instructions how to fix.

Compilation error: startup failed:
E:...Workspace\test\target\work\plugins\resources-1.2.1\src\groovy\org\grails\plugin\resource\ResourceProcessor.groovy: 6: unable to resolve class org.codehaus.groovy.grails.plugins.PluginManagerHolder
 @ line 6, column 1.
   import org.codehaus.groovy.grails.plugins.PluginManagerHolder
   ^
E:...Workspace\test\target\work\plugins\resources-1.2.1\src\groovy\org\grails\plugin\resource\util\HalfBakedLegacyLinkGenerator.groovy: 3: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
 @ line 3, column 1.
   import org.codehaus.groovy.grails.commons.ConfigurationHolder
   ^
2 errors

**Comment by flerro** [comment]
+1 same issue on clean Grails 2.4.3 project.  Thanks

**Comment by amra** [comment]
The source of this issue is described here: http://stackoverflow.com/a/23915908/304285
